
import { useEffect, useState } from "react";
import api from "../../services/api";
import jsPDF from "jspdf";

function IncidentReport() {
  const [attack, setAttack] = useState(null);

useEffect(() => {
  loadLatestAttack();
}, []);

const loadLatestAttack = async () => {
  try {
    const res = await api.get("/attacks");

    if (res.data.length > 0) {
      setAttack(res.data[0]);
    }
  } catch (err) {
    console.log(err);
  }
};

  const downloadReport = () => {

    const pdf = new jsPDF();

    pdf.setFontSize(22);
    pdf.text("CyberShield AI", 20, 20);

    pdf.setFontSize(18);
    pdf.text("Incident Report", 20, 35);

    pdf.setFontSize(12);

   pdf.text(
  `Attack Type: ${attack?.attack || "N/A"}`,
  20,
  70
);

pdf.text(
  `Confidence: ${attack?.confidence || 0}%`,
  20,
  85
);

pdf.text(
  `Severity: ${attack?.severity || "N/A"}`,
  20,
  100
);

pdf.text(
  `Source IP: ${attack?.ip || "N/A"}`,
  20,
  115
);
    
    pdf.text(
      "Recommended Actions",
      20,
      140
    );

    pdf.text(
      "• Block Source IP",
      30,
      155
    );

    pdf.text(
      "• Enable Firewall Protection",
      30,
      170
    );

    pdf.text(
      "• Notify SOC Team",
      30,
      185
    );

    pdf.text(
      "• Capture Network Packets",
      30,
      200
    );
    pdf.setFontSize(10);

pdf.text(
  "Generated by CyberShield AI",
  20,
  235
);

pdf.text(
  "AI-Powered Network Intrusion Detection System",
  20,
  242
);

    pdf.save("CyberShield_Incident_Report.pdf");

  };

  return (

    <div
      style={{
        background: "#1E293B",
        padding: "20px",
        borderRadius: "12px",
        marginTop: "20px",
      }}
    >
      <button
        onClick={downloadReport}
        style={{
          padding: "14px 28px",
          background: "#2563EB",
          color: "white",
          border: "none",
          borderRadius: "8px",
          cursor: "pointer",
          fontSize: "16px",
          fontWeight: "bold",
        }}
      >
        📄 Download Incident Report
      </button>
    </div>

  );

}

export default IncidentReport;